# General system-level configuration

{ config, pkgs, lib, extraPkgs, settings, ... }: let primaryUser = "sootpaws"; in {
    # Keep any system-level state compatible with this version
    system.stateVersion = "23.05";

    # Enable flakes
    nix.settings.experimental-features = [ "nix-command" "flakes" ];

    # Enable automatic nix store cleaning
    nix.gc.automatic = true;
    nix.gc.dates = "weekly";
    nix.gc.options = "--delete-older-than 30d";

    # Force users and groups to be consistant with this configuration
    users.mutableUsers = false;

    # Basic setup for main user
    users.users.primary = {
        isNormalUser = true;
        name = primaryUser;
        description = primaryUser;
        hashedPassword = (import ../private.nix).mainHashedPassword;
        extraGroups = [ "wheel" "networkmanager" "video" ];
    };

    # Use Home Manager for user configuration
    # imports = [
    #     extraPkgs.homeManager.nixosModules.home-manager {
    #         home-manager.extraSpecialArgs = {
    #             inherit settings primaryUser;
    #         };
    #         home-manager.useGlobalPkgs = true;
    #         home-manager.users.primary = import ./home/graphical;
    #     }
    # ];

    # Basic packages for managing configuration
    environment.systemPackages = with pkgs; [
        git
        gnumake
    ];

    # Set MOTD to show on login
    # The motd.nix file is generated by the makefile just before
    # invoking nixos-rebuild, and immidiately cleaned up afterward
    users.motd = import ../motd.nix;

    # Configure networking
    networking = {
        inherit (settings) hostName;
        networkmanager.enable = true;
    };

    # Time zone
    time.timeZone = "America/New_York";

    # Internationalisation
    i18n = let locale = "en_US.UTF-8"; in {
        defaultLocale = locale;
        extraLocaleSettings = {
            LC_ADDRESS = locale;
            LC_IDENTIFICATION = locale;
            LC_MEASUREMENT = locale;
            LC_MONETARY = locale;
            LC_NAME = locale;
            LC_NUMERIC = locale;
            LC_PAPER = locale;
            LC_TELEPHONE = locale;
            LC_TIME = locale;
        };
    };
}
